### ISSUE TITLE
What is import constrained_mst as cmst ?

### ISSUE THREAD

**Issue by rena-ganba** [constantinpape/mutex-watershed#1]
We encounter 

`import constrained_mst as cmst`
in test_b2a.py

So, what is it actually?

**Comment by constantinpape** [comment]
This repository is not well supported.
If you want to use the mutex-watershed please check out

https://github.com/hci-unihd/mutex-watershed

For examples on how to run the algorithm check e.g.
https://github.com/hci-unihd/mutex-watershed/blob/master/experiments/isbi/run_mws.py#L6
